# Generated by Django 3.1.7 on 2021-03-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор комментария')),
                ('post_date', models.DateField(auto_now=True, verbose_name='Дата оставления комментария')),
                ('related_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='Статья для которой оставлен комментарий')),
            ],
        ),
    ]
