# Generated by Django 3.1.7 on 2021-03-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='', verbose_name='Текст комментария'),
        ),
    ]
